filebeat.inputs:

# Prospectors
- type: filestream
  id: nodejs-filestream
  tags: ["nodejs"]
  paths:
    - ingest_data/node/*.json
  parsers:
    - multiline:
        type: pattern
        pattern: '.'
        match: after
        max_lines: 100000
    - ndjson:
        target: "message"
        add_error_key: true
  pipeline: "idc_node_18_audit_pipeline"
  index: "idc_node_18_audit_index"

- type: filestream
  id: java-filestream
  tags: ["java"]
  paths:
    - ingest_data/java/*.json
  parsers:
    - multiline:
        type: pattern
        pattern: '.'
        match: after
        max_lines: 100000
    - ndjson:
        target: "message"
        add_error_key: true
  pipeline: "idc_java_audit_pipeline"
  index: "idc_java_audit_index"

- type: filestream
  id: commits-filestream
  tags: ["commits"]
  paths:
    - ingest_data/git/commits/*.json
  parsers:
    - multiline:
        type: pattern
        pattern: '.'
        match: after
        max_lines: 10000000
    - ndjson:
        target: "message"
        add_error_key: true
  pipeline: "idc_git_commits_pipeline"
  index: "idc_git_commits_index"

- type: filestream
  id: git-info-filestream
  tags: ["git-info"]
  paths:
    - ingest_data/git/info/*.json
  parsers:
    - multiline:
        type: pattern
        pattern: '.'
        match: after
        max_lines: 1000000
    - ndjson:
        target: "message"
        add_error_key: true
  pipeline: "idc_git_info_pipeline"
  index: "idc_git_info_index"

- type: filestream
  id: gitleaks-filestream
  tags: ["gitleaks"]
  paths:
    - ingest_data/gitleaks/*.json
  parsers:
    - multiline:
        type: pattern
        pattern: '.'
        match: after
        max_lines: 100000
  pipeline: "idc_git_leaks_pipeline"
  index: "idc_git_leaks_index"

- type: filestream
  id: python-filestream
  tags: ["python"]
  paths:
    - ingest_data/python/*.json
  parsers:
    - multiline:
        type: pattern
        pattern: '.'
        match: after
        max_lines: 1000000
    - ndjson:
        target: "message"
        add_error_key: true
  pipeline: "idc_python_audit_pipeline"
  index: "idc_python_audit_index"

- type: filestream
  id: terraform-filestream
  tags: ["terraform"]
  paths:
    - ingest_data/terraform/*.json
  parsers:
    - multiline:
        type: pattern
        pattern: '.'
        match: after
        max_lines: 100000
    - ndjson:
        target: "message"
        add_error_key: true
  pipeline: "idc_terraform_pipeline"
  index: "idc_terraform_index"

# https://www.elastic.co/guide/en/beats/filebeat/8.9/configuration-autodiscover.html
filebeat.autodiscover:
  providers:
    - type: docker
      # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html
      hints.enabled: true

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD} 

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

setup:
  template.enabled: false
  ilm.enabled: false
