version: '3'

services:

  dependency-checks-go:
    build: ./dependencies/go
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

  dependency-checks-java:
    build: ./dependencies/java
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

  dependency-checks-kotlin:
    build: ./dependencies/kotlin
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

  dependency-checks-node:
    build: ./dependencies/node
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

  dependency-checks-perl:
    build: ./dependencies/perl
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

  dependency-checks-php:
    build: ./dependencies/php
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

  dependency-checks-python:
    build: ./dependencies/python
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

  dependency-checks-ruby:
    build: ./dependencies/ruby
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

  dependency-checks-csharp:
    build: ./dependencies/csharp
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

  # vulnerability-checks-docker:
  #   build: ./vulnerabilities/docker
  #   volumes:
  #     - ./reports:/idc/reports
  #     - ./repos:/idc/repos
  #     - ./utils:/idc/utils
  #     - /var/run/docker.sock:/var/run/docker.sock

  vulnerability-checks-terraform:
    build: ./vulnerabilities/terraform
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

  vulnerability-checks-gitleaks:
    build: ./vulnerabilities/gitleaks
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

  support-git-commits:
    build: ./support/git
    volumes:
      - ./reports:/idc/reports
      - ./repos:/idc/repos
      - ./utils:/idc/utils

volumes:
    reports:
    repos:
    utils:
